name: servit_project_version_2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  extended_image: ^8.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.8
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  form_inputs:
    path: packages/form_inputs
  formz: ^0.7.0
  gap: ^3.0.1
  geolocator: ^11.0.0
  get_it: ^7.6.6
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/