// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3nQvWr2FUVBrn_622nMGpCRSkHS6Cg_A',
    appId: '1:90996887838:web:3edb2f77e3527f4b70790f',
    messagingSenderId: '90996887838',
    projectId: 'servit-2',
    authDomain: 'servit-2.firebaseapp.com',
    storageBucket: 'servit-2.appspot.com',
    measurementId: 'G-9MPNHE9YW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwPP4c0CYyD81VEFEnPVKWwNO_oTqJdU',
    appId: '1:90996887838:android:319390ea7c952c2570790f',
    messagingSenderId: '90996887838',
    projectId: 'servit-2',
    storageBucket: 'servit-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOiCINv18mrJZIDcizZb--2TLyVd3zsA',
    appId: '1:90996887838:ios:536992ea47c1a39070790f',
    messagingSenderId: '90996887838',
    projectId: 'servit-2',
    storageBucket: 'servit-2.appspot.com',
    iosBundleId: 'com.example.servitProjectVersion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOiCINv18mrJZIDcizZb--2TLyVd3zsA',
    appId: '1:90996887838:ios:0cb401f07d07938470790f',
    messagingSenderId: '90996887838',
    projectId: 'servit-2',
    storageBucket: 'servit-2.appspot.com',
    iosBundleId: 'com.example.servitProjectVersion2.RunnerTests',
  );
}
